### ISSUE TITLE
Atom Feed brings strange results after adding a link

### ISSUE THREAD

**Issue by mro** [mro/Shaarli-API-test#1]
see the [build failure](https://travis-ci.org/mro/Shaarli-API-test/jobs/79034324#L363) and the [test case `test-post.sh`](https://github.com/mro/Shaarli-API-test/blob/master/scripts/test-post.sh)

**Comment by mro** [comment]
tracked down to

- [test failure, e.g. v0.5.3](https://travis-ci.org/mro/Shaarli-API-test/jobs/79034324#L455) - uses 'cached' version (which cannot be true anyway because it shows only the **new** entry and the private link)
- [code suggesting not to cache when logged in](https://github.com/shaarli/Shaarli/blob/v0.5.3/index.php#L773)

**Comment by virtualtam** [comment]
> not to cache when logged in

I think that for a feed to be cached (this concerns Atom, RSS, and Daily RSS), it has to be accessed first by an anonymous user, and will then be served to future anonymous requesters.

Though the code for caching pages has been refactored and polished, the calling logic has be left untouched and may be sub-optimal.

quick questions about what's happening on the build server:
- does the `pagecache` dir exist?
- is it write-able?
- does Shaarli write stuff within it?

quick question about the test script: wouldn't it by any chance be overriding the default public link?

**Comment by mro** [comment]
> does the `pagecache` dir exist?

if it's part of the source tar ball.

> is it write-able?

exactly how it's in the source tar ball.

> does Shaarli write stuff within it?

no idea, but I guess - why else would it say '…Cached…' in the http response.

> wouldn't it by any chance be overriding the default public link?

it just does a 'add link' operation. I have no idea what the server does with that.

**Comment by virtualtam** [comment]
other guess: could the script be redirected to the `edit` form of the existing public link, instead of the `add` form?

**Comment by virtualtam** [comment]
Off-topic question, which is more of a design one: why choosing bash+curl+xslt to script tests, and not a high-level scripting language with HTTP session handling & HTML/XML parsing?

**Comment by mro** [comment]
> other guess: could the script be redirected to the edit form of the existing public link, instead of the add form?

here's the [full take](https://travis-ci.org/mro/Shaarli-API-test/jobs/78946287#L654) of the final http POST.

I read the [called operation](https://travis-ci.org/mro/Shaarli-API-test/jobs/78946287#L672) a `save_edit=Save` - so I'd say no.

**Comment by mro** [comment]
> Off-topic question, which is more of a design one: why choosing bash+curl+xslt to script tests, and not a high-level scripting language with HTTP session handling & HTML/XML parsing?

Personal taste. I prefer going lightweight and not install gazillions of 3rd-party bugs, but rather use low-level, proven tools with as few magic as possible.

**Comment by mro** [comment]
caution: just updated the links in https://github.com/mro/Shaarli-API-test/issues/1#issuecomment-138128767 - they were wrong before.

**Comment by virtualtam** [comment]
Could you run the tests with the following 3 revisions added to the test matrix?
- 5ac5349ac053b1e560b136c62f8c764fd3230039 - precedes cache method refactoring
- 01e48f269df59e02798dad4a698c125d76b0ed70 - introduction of CachedPage class
- aedd62e2b84b4ea0d3c03f5c23ec594f4ebb1c17 - cache cleanup update

**Comment by mro** [comment]
hold on a second...

**Comment by mro** [comment]
in short: the bug is older.

**Comment by virtualtam** [comment]
Yep, I was monitoring build 163.

A dichotomy between 0.0.45beta and v0.5.0 will be required to rootcause the issue.

The first potential culprits are all commits related to `showATOM`, hence `LinkDB`:
- cbecab773526b0c39f3cffa1d4595b5caa781bda - before LinkDB refactoring
- ca74886f30da323f42aa4bd70461003f46ef299b - LinkDB refactoring + test coverage
- 9c8752a2061e67c719125edb6e0d6717d1af8553 - LinkDB global var removal
- a037ac6963f111d0c9d5e4faa55f805edd93d91b - don't load hidden links

**Comment by virtualtam** [comment]
> It's even older than 0.5.0 - are you testing me?

Sorry for this one, I had 0.5.3 in mind.

> other guess: could the script be redirected to the edit form of the existing public link, instead of the add form?

Your test script need some sleep (and so do I); see my answer on shaarli/Shaarli/issues/347:

>The test script is too fast emitting requests.

>Per shaarli/Shaarli/pull/238 the 2 default links are created:
- using the current date minus 1 minute for the private link
- using the current date YYYYMMDD_HHmm**SS** for the public link

>The POST request is very likely to entail the creation of a new link with **the same timestamp** as the default public link, thus overwrites it when saving.

>I've forked the API tester and added `sleep`s between requests: https://travis-ci.org/virtualtam/Shaarli-API-test/builds/79055902

**Comment by mro** [comment]
fixed in pull request https://github.com/shaarli/Shaarli/pull/348 to upstream.
