### ISSUE TITLE
current master fails test

### ISSUE THREAD

**Issue by mro** [mro/Shaarli-API-test#6]
failing build: https://travis-ci.org/mro/Shaarli-API-test/builds/121898355
failing commit: https://github.com/shaarli/Shaarli/commit/d92169c or earlier

**Comment by mro** [comment]
@ArthurHoaro the [redirect location for failing logins](https://travis-ci.org/mro/Shaarli-API-test/jobs/130665858#L218) has changed in https://github.com/shaarli/Shaarli/archive/v0.7.0 – (an additional `GET` parameter). That's a change of the HTTP interface, so the test has to trigger. How would you recommend to handle such cases in tests that also have to cover legacy versions?

**Comment by mro** [comment]
distinguish from  #5, ensure those fixes made it into 592d535

**Comment by ArthurHoaro** [comment]
Yes there is a new parameter when the login fails. From what I see you can go with a regex instead of the exact string. However, the day we'll switch to real error messages instead of alerts, it won't work.

**Comment by mro** [comment]
thx, will there be an announcement of the upcoming error message so as e.g. @dimtion and I can prepare our respective client Apps to properly handle the new errors as well as the old ones once they get released? May @dimtion and I be heard when designing the new error messages?

**Comment by mro** [comment]
@ArthurHoaro does 0bdae1fa0c05 make sense to you?

**Comment by ArthurHoaro** [comment]
No problem. There are only `FIXME!` in the code yet, but I'll probably work on it along with the new design, which leave us a few months.

**Comment by ArthurHoaro** [comment]
I'm not good enough in shell to answer that. I'll let you test it.

**Comment by mro** [comment]
> real error messages instead of alerts

@ArthurHoaro @dimtion what may that look like? Setting a (additional?) HTTP Response Header with an error message would be super helpful. It may even be the HTTP status code's reason phrase itself.

**Comment by ArthurHoaro** [comment]
HTTP protocol isn't supposed to handle functional errors. However, I was thinking of it, and it might not be a problem. The current theme will still be supported in the main repo, even if not set as default. So you'll only have to change the default theme with your tests, and everything should still work.

**Comment by mro** [comment]
> HTTP protocol isn't supposed to handle functional errors.

Sorry, I don't understand your point. A protocol never handles anything, it just reports.

> So you'll only have to change the default theme with your tests, and everything should still work.

Sorry, I don't understand of what benefit that should be.

**Comment by ArthurHoaro** [comment]
> A protocol never handles anything, it just reports.

What I meant is that HTTP protocol, and [its codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), isn't made for functional reports.

> Sorry, I don't understand of what benefit that should be.

Nevermind, I was only thinking about the tests.

**Comment by mro** [comment]
> HTTP protocol, and its codes, isn't made for functional reports.

I understand the HTTP status reason phrases are meant to be meaningful in the application domain, [RFC 7231 section 6.1](https://tools.ietf.org/html/rfc7231#section-6.1) says:

> The reason phrases listed here are only recommendations – they can be replaced by local equivalents without affecting the protocol.

where I interpret *local* as *from the application domain*.

So my understanding is, that the HTTP status reason phrases can legitimately be used to report whatever the server wants in a machine readable, invisible manner defined by the application alone. That's ideal for non-human (non-browser) callers of the HTTP endpoint.

This may not be mainstream, but it's both helpful without side effects and explicitly allowed by the (HTTP) protocol definition.
