### ISSUE TITLE
New client can't login

### ISSUE THREAD

**Issue by frantz2mars** [mro/Shaarli-API-test#8]
![IMG_BF4E619B90F2-1](https://user-images.githubusercontent.com/50201251/57218283-3ba74780-6ff5-11e9-860c-8e29ade959a4.jpeg)

Hi I can't login with ShaarliO to my Shaarli 0.10.4 https://frantz.fr/liens/
I tried with an iPad and an iPhone both running iOS 12.2
I tried a simpler password without special characters
I even tried to use the secret API key instead of my pwd...

**Comment by frantz2mars** [comment]
I went to Apple for a refund. Have a nice day...

**Comment by mro** [comment]
Sorry for the inconvenience, you got the refund?
